In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset=pd.read_csv('/kaggle/input/insurance/insurance.csv')

In [3]:
dataset.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [5]:
dataset.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [6]:
num_cols=dataset.select_dtypes(include='number').columns.tolist()
cat_cols=dataset.select_dtypes(include='object').columns.tolist()

In [7]:
print(num_cols)

['age', 'bmi', 'children', 'charges']

In [8]:
print(cat_cols)

['sex', 'smoker', 'region']

In [14]:
dataset['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [15]:
dataset['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

for col in num_cols:
    le=LabelEncoder()
    le.fit(dataset[col].drop_duplicates())
    dataset[col]=le.transform(dataset[col])

In [ ]:
f,ax=plt.subplots(figsize=(10,8))
corr=dataset.corr()
sns.heatmap(corr, annot=True, cmap="YlGnBu",square=True,ax=ax,mask=np.zeros_like)