In [22]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
import warnings
warnings.filterwarnings('ignore')
from hyperopt import STATUS_OK,Trials,fmin,hp,tpe,space_eval

In [23]:
df=pd.read_csv('craigslistVehicles.csv')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525839 entries, 0 to 525838
Data columns (total 22 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   url           525839 non-null  object
 1   city          525839 non-null  object
 2   city_url      525839 non-null  object
 3   price         525839 non-null  int64
 4   year          524399 non-null  float64
 5   manufacturer  501260 non-null  object
 6   make          517201 non-null  object
 7   condition     279881 non-null  object
 8   cylinders     315439 non-null  object
 9   fuel          521544 non-null  object
 10  odometer      427248 non-null  float64
 11  title_status  523014 non-null  object
 12  transmission  521572 non-null  object
 13  VIN           305650 non-null  object
 14  drive         374475 non-null  object
 15  size          174519 non-null  object
 16  type          376906 non-null  object
 17  paint_color   354306 non-null  object
 18  image_url     525831 non-null  object
 19  desc          525815 non-null  object
 20  lat           513618 non-null  float64
 21  long          513618 non-null  float64
dtypes: float64(4), int64(1), object(17)
memory usage: 88.3+ MB

In [25]:
df.head(1)

,url,city,city_url,price,year,manufacturer,make,condition,cylinders,fuel,odometer,title_status,transmission,VIN,drive,size,type,paint_color,image_url,desc,lat,long
0,https://grandrapids.craigslist.org/cto/d/hasti...,"grand rapids, MI",https://grandrapids.craigslist.org,1500,2006.0,cadillac,cts,good,6 cylinders,gas,236000.0,clean,automatic,NaN,rwd,mid-size,coupe,blue,https://images.craigslist.org/00K0K_a9CZoZg2U8...,"2006 CtS Leather, Runs and drives Good.236k mil",42.643,-85.2937

In [26]:
cols_to_be_dropped=['url','city','city_url','image_url','lat','long','desc','title_status','VIN','size','make']
for col in cols_to_be_dropped:
    df.drop(col,axis=1,inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525839 entries, 0 to 525838
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         525839 non-null  int64
 1   year          524399 non-null  float64
 2   manufacturer  501260 non-null  object
 3   condition     279881 non-null  object
 4   cylinders     315439 non-null  object
 5   fuel          521544 non-null  object
 6   odometer      427248 non-null  float64
 7   transmission  521572 non-null  object
 8   drive         374475 non-null  object
 9   type          376906 non-null  object
 10  paint_color   354306 non-null  object
dtypes: float64(2), int64(1), object(8)
memory usage: 44.1+ MB

In [28]:
df.isnull().sum()

price                0
year              1440
manufacturer     24579
condition       245958
cylinders       210400
fuel              4295
odometer         98591
transmission      4267
drive           151364
type            148933
paint_color     171533
dtype: int64

In [29]:
df=df.dropna()
df.head()

,price,year,manufacturer,condition,cylinders,fuel,odometer,transmission,drive,type,paint_color
0,1500,2006.0,cadillac,good,6 cylinders,gas,236000.0,automatic,rwd,coupe,blue
5,4950,2010.0,subaru,good,4 cylinders,gas,253000.0,automatic,4wd,sedan,white
6,6850,2007.0,gmc,good,8 cylinders,gas,254000.0,automatic,4wd,wagon,black
7,7995,2007.0,lexus,excellent,6 cylinders,gas,146111.0,automatic,fwd,sedan,white
8,4995,2011.0,hyundai,excellent,4 cylinders,gas,115048.0,automatic,fwd,sedan,blue

In [30]:
df.isnull().sum()

price           0
year            0
manufacturer    0
condition       0
cylinders       0
fuel            0
odometer        0
transmission    0
drive           0
type            0
paint_color     0
dtype: int64

In [31]:
df.shape

(144903, 11)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 144903 entries, 0 to 525836
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   price         144903 non-null  int64
 1   year          144903 non-null  float64
 2   manufacturer  144903 non-null  object
 3   condition     144903 non-null  object
 4   cylinders     144903 non-null  object
 5   fuel          144903 non-null  object
 6   odometer      144903 non-null  float64
 7   transmission  144903 non-null  object
 8   drive         144903 non-null  object
 9   type          144903 non-null  object
 10  paint_color   144903 non-null  object
dtypes: float64(2), int64(1), object(8)
memory usage: 13.3+ MB